name: Build & Test

on:
  pull_request:
    branches: [ develop ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21' # Make sure to specify the current version of Go the project is using

    - name: Lint
      run: make lint

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
